### ISSUE TITLE
last_run_summary.yaml path changes with puppet 7.0

### ISSUE THREAD

**Issue by chris240189** [kuhn-ruess/Checkmk-Checks#20]
taken from the release notes of puppet 7.0
https://puppet.com/docs/puppet/7.0/release_notes_puppet.html

_Public folder

There is a new folder with 0755 access rights named public, which is now the default location for the last_run_summary.yaml report. It has 640 file permissions. This makes it possible for a non-privileged process to read the file. To relax permissions on the last run summary, set the group permission on the file in puppet.conf to the following PUP-10627: lastrunsummary = $publicdir/last_run_summary.yaml { owner = root, group = monitoring, mode = 0640 }_

**Comment by Bastian-Kuhn** [comment]
Hi Chris,

Thanks for this information. But since I am not having a puppet environment to test, it would be nice
if you can make pull request for that change, which you have tested before.

**Comment by Bastian-Kuhn** [comment]
Thank you :)
