### ISSUE TITLE
Small typo and issue with pgrep

### ISSUE THREAD

**Issue by dnlldl** [kuhn-ruess/Checkmk-Checks#37]
I suggest fixing the typo `assined` to `assigned` in the check output. Also, for my specific system (Unraid), I had to change the `pgrep` query a little bit:
`PID=$(pgrep -f -- "qemu-system-x86_64 .*-name guest=$NAME")`

Since this depends heavily on which version/system qemu is running on... I suggest adding multiple ways of trying to find the PIDs or find a better and universal one. An example (this is NOT perfect either): https://www.seei.biz/find-the-pid-and-names-of-virtual-machines-on-centos-7/

finally, I added `--all` to `virsh list` to be able to see stopped VMs as well, rather than getting UNKN alerts because they wouldn't show in the output in my case

**Comment by Bastian-Kuhn** [comment]
Hi, thank you very much for the Feedback. Since I don't have such a system nor can test it, would it be possible to provide a Pull Request with the suggested changes? 

Best Bastian

**Comment by Bastian-Kuhn** [comment]
Inactive
