### ISSUE TITLE
ImportError: cannot import name 'perfometers' from 'cmk.gui.plugins.views.perfometers' (unknown location)

### ISSUE THREAD

**Issue by xtforever** [kuhn-ruess/Checkmk-Checks#39]
file: web/plugins/perfometer/mysql_status.py
checkmk: 2.1

Maybe this will work:

# Perf-O-Meter for mysql_status
# issue #24
from cmk.gui.plugins.views.perfometers.utils

**Comment by Bastian-Kuhn** [comment]
Hello,

the Version 4.0 of the Plugin has the Fixes from #24, but if you experience this error with 2.1, that would mean they moved again something. I currently more than busy, so a quick question: Are you saying you fixed it by importing from cmk.gui.plugins.views.perfometers.utils? If so, I would change that and release a cmk 2.1 version of the plugin. 

Thanks for your Help!

**Comment by Bastian-Kuhn** [comment]
Fixed in 4.0.1 version of the Plugin. The Path was changed again in Checkmk...
