### ISSUE TITLE
Possible to add volume information to pure?

### ISSUE THREAD

**Issue by mfaust78** [kuhn-ruess/Checkmk-Checks#41]
Pure check for CheckMK is cool, but lacks Volume / Array usage data.
Would it be possible to add that?
Based on the Pure Storage FlashArray REST Client it seams possible to get array space data (GET https://array.example.com/api/1.19/array?space=true) as well as volume space data (GET https://array.example.com/api/1.19/volume?space=true).
Now sure if the Python library allow/manages that.

**Comment by Bastian-Kuhn** [comment]
Hello, 
I guess it would. But I develop these plugins only during consulting. Main Reasons is that I have none of these devices myself, while when on Consumer site I just can access them.

**Comment by carkle1971** [comment]
Added volumes, replace agent_pure with the changed one. You will see volumes and used space and so on. It show in TB in PB now but that is works in progress. So is the performance stats. I am working on that.  
https://github.com/carkle1971/Scripts/tree/main/CheckMK/PureStorage

**Comment by Bastian-Kuhn** [comment]
Got no Pull request yet

**Comment by Bastian-Kuhn** [comment]
done, thanks again :)
