### ISSUE TITLE
CheckMK Discovery failed

### ISSUE THREAD

**Issue by righter83** [kuhn-ruess/Checkmk-Checks#48]
Hi 

First thanks for that plugin!

It is working on my site pretty well but the discovery fails with this message:

`no unmonitored services found, no vanished services found, no new host labels, Parsing of section pure_arraydetails failed`

**Comment by righter83** [comment]
Sure, how can I get that trace? I don't find a crash report

**Comment by Bastian-Kuhn** [comment]
Pls first try the 1.2 Version if possible. There was an recent incoming pull request for this plugin.

**Comment by Bastian-Kuhn** [comment]
If you can send me the Agent Output (mail@bastian-kuhn.de) I will build a fix.

**Comment by Bastian-Kuhn** [comment]
Fixed
