### ISSUE TITLE
wrong size

### ISSUE THREAD

**Issue by righter83** [kuhn-ruess/Checkmk-Checks#49]
Hi

another thing, it shows me 1000x bigger volume as they are
![image](https://user-images.githubusercontent.com/12727740/229538438-a897f127-3a4d-4d9c-be33-78ba727aa518.png)
The volume has only 4TB size not 4PB :-)

**Comment by Bastian-Kuhn** [comment]
Hi, is this the pure plugin?
Can you please try the previous version?

**Comment by righter83** [comment]
Yes it is the pure plugin.

I tried now the version 1.2 but same result:
`8.17% used (334.77 TB of 4.00 PB)`

**Comment by Bastian-Kuhn** [comment]
Hello, there is now a 1.3.1 for testing

**Comment by righter83** [comment]
Hi

same wrong sizes with 1.3.1

**Comment by Bastian-Kuhn** [comment]
That is supposed to be fixed meanwhile
