### ISSUE TITLE
pure - A section for the SSL certs 

### ISSUE THREAD

**Issue by SteveParker8x8** [kuhn-ruess/Checkmk-Checks#53]
Hi , 
I had a request to have a check for the pure storage array to alert when the SSL certs are approaching expiry .
I have the code to hand and can submit a Pull Request if this would help?

Thanks for the continued work on the Checkmk-Checks

Steve

**Comment by Bastian-Kuhn** [comment]
Hi Steve,

It would be more than welcome :) 
Thanks for your time too, and I'm looking forward to this Pullrequest. 

 Bastian

**Comment by SteveParker8x8** [comment]
Thanks Bastian, can you grant the appropriate access....
```
git push --set-upstream origin add_cert_check
ERROR: Permission to kuhn-ruess/Checkmk-Checks.git denied to SteveParker8x8.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Bastian-Kuhn** [comment]
Hi Steve, you have to fork the Repo, commit in your repo (rebase it, if we made changes in the meantime) and then create the Request best using the Web interface (There will be a prompt). See also here: https://opensource.com/article/19/7/create-pull-request-github

Don't worry, it's easy, and your commits will then go into our repo.
