### ISSUE TITLE
Docker check-mk 2.2 fails to pre-compile after mkp install of pure 1.4.5

### ISSUE THREAD

**Issue by zbukhari-apex** [kuhn-ruess/Checkmk-Checks#69]
The error message reads:

`Error precompiling checks for host PURE.STORAGE.HOST: Cannot find check file agent_pure needed for check type agent_pure.`

So I went into the checks directory and found `pure_agent` but not `agent_pure`. I just renamed it and then it worked.

```
$ cd /omd/sites/cmk/local/share/check_mk/checks
$ mv pure_agent agent_put
```

**Comment by Bastian-Kuhn** [comment]
Is fixed in 1.4.7, can you check if that breaks something? In your case, you may need to remove your agent_pure you created with mv because that can cause a conflict.
