### ISSUE TITLE
Pure Issue 

### ISSUE THREAD

**Issue by X-gen76** [kuhn-ruess/Checkmk-Checks#75]
I'm trying to add a pure host to one of checkmk instances but I get the following error when running the tests in Checkmk.
Any idea how to solve this?

Agent exited with code 1: Traceback (most recent call last):
File "/omd/sites/vali/local/share/check_mk/agents/special/agent_pure", line 33, in <module>
FA = purestorage.FlashArray(HOSTNAME, api_token=API_TOKEN)
^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'purestorage' has no attribute 'FlashArray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/omd/sites/vali/local/share/check_mk/agents/special/agent_pure", line 40, in <module>
except purestorage.purestorage.PureError as error_txt:
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'purestorage' has no attribute 'purestorage'

**Comment by Bastian-Kuhn** [comment]
I don't have a Pure Storage Device here to test, but looks to me like a Problem with the Python Module for pure storage.
Maybe wrong version.
